Repository bullet-train-co/bullet_train, pull requests merged in 2023-08, with the labels that each got.

#743 Update develop rake task to hack
  bin/hack
Labels: Joint PR, Merged Elsewhere

#728 Enable password field tests, move Super Scaffolding file tests
  test/bin/setup-super-scaffolding-system-test
  test/system/super_scaffolding_partial_test.rb
Labels: Merge Conflict

#741 Tests for resending invitations
  test/system/invitations_test.rb
Labels: Joint PR, Merged Elsewhere

#705 Add initializer for Bullet Train configuration
  config/initializers/bullet_train.rb
Labels: Joint PR

#706 Replace sidebar with navbar
  test/bin/setup-action-models-system-test
  test/bin/setup-audit-logs-system-test
  test/bin/setup-super-scaffolding-system-test
Labels: Joint PR

#891 Fix action model tests
  test/bin/setup-action-models-system-test
  test/system/action_models_test.rb
Labels: Joint PR

#725 Memberships API
  app/controllers/api/v1/memberships_controller.rb
  app/views/api/v1/memberships/_membership.json.jbuilder
  app/views/api/v1/open_api/index.yaml.erb
  test/factories/memberships.rb
Labels: Joint PR

#732 Use new API attribute method in controller tests
  test/controllers/api/v1/platform/access_tokens_controller_test.rb
  test/controllers/api/v1/scaffolding/completely_concrete/tangible_things_controller_test.rb
Labels: Joint PR

#791 Add option to hide developer menu
  app/views/account/shared/_menu.html.erb
  test/system/application_platform_test.rb
  test/system/webhooks_system_test.rb
Labels: Joint PR

#749 Fix: OpenAPI warnings
  .redocly.yaml
  Gemfile.lock
  bin/configure
  test/controllers/api/open_api_controller_test.rb
  test/factories/webhooks/outgoing/events.rb
Labels: Joint PR

#899 Add configuration for incoming webhook parent class
  config/initializers/bullet_train.rb
Labels: Joint PR

#737 Invitations API
  app/controllers/api/v1/invitations_controller.rb
  app/models/ability.rb
  app/views/api/v1/invitations/_invitation.json.jbuilder
  app/views/api/v1/open_api/index.yaml.erb
  app/views/api/v1/open_api/invitations/_paths.yaml.erb
  test/factories/invitations.rb
Labels: Joint PR

#915 Fix: 912 — OpenAPI test failure
  app/views/api/v1/open_api/invitations/_paths.yaml.erb
  test/controllers/api/open_api_controller_test.rb
Labels: Joint PR
